int				tolower(int c);
int				isprint(int c);
int				toupper(int c);
int				isalpha(char c);
int				isdigit(char c);
int				strlen(char *str);
void            ft_putnbr(int nb);
int				isalnum(char *str);
int				ft_atoi(char *str);
char			*strdup(const char *s);
int				strcmp(char *s1, char *s2);
char			*strstr(char *str, char *to_find);
char			*strcat(char *dest, char *src);
char			*strcpy(char *dest, char *src);
char			*strncpy(char *dest, char *src, unsigned int n);
unsigned int	ft_strlcat(char *dest, char *src, unsigned int size);
int				strncmp(const char *s1, const char *s2, unsigned int n);